version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "sunil-blue-task"
        LoadBalancerInfo:
          ContainerName: "sunilcontainer001"
          ContainerPort: 80
