--- 
Resources: 
  - 
    TargetService: 
      Properties: 
        LoadBalancerInfo: 
          ContainerName: sunilcontainer001
          ContainerPort: 80
        TaskDefinition: sample-website
      Type: "AWS::ECS::Service"
version: 0.0
