version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:165306929646:task-definition/sunil-ecs-demo-task:1"
        LoadBalancerInfo:
          ContainerName: "sunilcontainer"
          ContainerPort: 80
