version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - eval `aws ecr get-login --no-include-email --region us-east-1`
      - REPOSITORY_URI=165306929646.dkr.ecr.us-east-1.amazonaws.com/firstbuild
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest 
	  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $REPOSITORY_URI:latest
